name: RISE-Universal-Hubs-beta

pool:
  name: RSConnect

trigger:
  branches:
    include:
    - beta # this needs to be either main OR master depending on what your project uses
  paths:
    exclude:
    - azure-pipelines-beta.yml
    - azure-pipelines.yml

resources:
  repositories:
    - repository: posit-deploy
      type: git
      name: 'Academies Intervention Team/posit-deploy'

extends:
  template: deploy.yml@posit-deploy
  parameters:
    appName: RISE-Universal-Hubs-beta # this will need replacing
    environments:
    - name: Staging
      appId: 1084 # this will need replacing if updating an existing app pipeline
    - name: Production
      appId: none
    approvers: |
      ben7.smith@education.gov.uk
      ben.clewarth@education.gov.uk
      James.micklefield@education.gov.uk
      
