name: RISE-Universal-Hubs-Beta

pool:
  name: RSConnect

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipelines.yml

resources:
  repositories:
    - repository: posit-deploy
      type: git
      name: 'Academies Intervention Team/posit-deploy'

extends:
  template: deploy.yml@posit-deploy
  parameters:
    appName: RISE-Universal-Hubs-beta
    environments:
    - name: Staging
      appId: 108
    - name: Pre-Production
      appId: 1097
    - name: Production
      appId: 544
    approvers: |
      ben7.smith@education.gov.uk
      ben.clewarth@education.gov.uk
      James.micklefield@education.gov.uk